// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';
import starlightLinksValidator from 'starlight-links-validator';
import { existsSync, readFileSync } from 'node:fs';
import { satteri } from '@astrojs/markdown-satteri';
import { defineHastPlugin } from 'satteri';

// Generated by scripts/api/generate.mjs; absent until the API reference has been generated.
const apiSidebar = existsSync('./src/api-sidebar.json')
? JSON.parse(readFileSync('./src/api-sidebar.json', 'utf8'))
: ['api-reference'];

// Rewrites guide links to pub.dev API docs onto our generated API pages (map from scripts/api/generate.mjs),
// and prefixes root links ("/start/") with the base path, so content works under /carp-docs-starlight.
// ponytail: regex on raw HTML nodes; drop the base part once docs.carp.dk serves from the root.
const apiLinks = existsSync('./src/api-links.json') ? JSON.parse(readFileSync('./src/api-links.json', 'utf8')) : {};
const base = (process.env.BASE_PATH ?? '/').replace(/\/$/, '');
const toApi = (v) => {
const m = v.match(/^https?:\/\/pub\.(?:dev|dartlang\.org)\/documentation\/([^/]+)\/[^/]+\/?([^#]*)/);
const path = m && (m[2] || 'index.html');
return (m && (apiLinks[`${m[1]}/${path}`] ?? apiLinks[`${m[1]}/~/${path.replace(/^[^/]+\//, '')}`])) ?? v; // #anchors dropped
};
const withBase = (v) => (/^\/(?!\/)/.test(v) && !v.startsWith(`${base}/`) ? base + v : v);
const fix = (v) => (typeof v === 'string' ? withBase(toApi(v)) : v);
const linksPlugin = defineHastPlugin({
name: 'api-and-base-links',
element: {
filter: ['a', 'img'],
visit(node, ctx) {
for (const k of ['href', 'src']) if (fix(node.properties[k]) !== node.properties[k]) ctx.setProperty(node, k, fix(node.properties[k]));
},
},
mdxJsxFlowElement: {
filter: ['LinkCard', 'LinkButton', 'a', 'img', 'video'],
visit(node, ctx) {
for (const a of node.attributes) if (['href', 'src'].includes(a.name) && fix(a.value) !== a.value) ctx.setProperty(node, a.name, fix(a.value));
},
},
raw(node, ctx) {
const value = node.value.replace(/(href|src)="([^"]*)"/g, (_, k, v) => `${k}="${fix(v)}"`);
if (value !== node.value) ctx.replaceNode(node, { type: 'raw', value });
},
});

const basePath = (process.env.BASE_PATH ?? '/').replace(/\/$/, '');

export default defineConfig({
	// GitHub Pages serves under /carp-docs-starlight until docs.carp.dk points to it.
	site: process.env.SITE_URL ?? 'https://docs.carp.dk',
	redirects: {
		'/carp-mobile-sensing/using-carp-mobile-sensing': `${basePath}/carp-mobile-sensing/runtime/client-and-study-controller/`,
		'/carp-mobile-sensing/software-architecture': `${basePath}/carp-mobile-sensing/architecture/`,
		'/carp-mobile-sensing/domain-model': `${basePath}/carp-mobile-sensing/domain/`,
		'/carp-mobile-sensing/measure-types': `${basePath}/carp-mobile-sensing/sampling-packages/available-packages/`,
		'/carp-mobile-sensing/data-managers': `${basePath}/carp-mobile-sensing/infrastructure/data-managers/`,
		'/carp-mobile-sensing/app-task-model': `${basePath}/carp-mobile-sensing/runtime/app-tasks/`,
		'/carp-mobile-sensing/data-transformation-and-privacy': `${basePath}/carp-mobile-sensing/domain/data-endpoints-and-privacy/`,
		'/carp-mobile-sensing/extending-carp-mobile-sensing': `${basePath}/carp-mobile-sensing/sampling-packages/create-your-own/`,
		'/carp-mobile-sensing/best-practice': `${basePath}/carp-mobile-sensing/run-in-production/`,
	},
	base: process.env.BASE_PATH ?? '/',
markdown: { processor: satteri({ hastPlugins: [linksPlugin] }) },
	integrations: [
		mermaid({ autoTheme: true }), // must come before starlight
		starlight({
			plugins: [starlightLinksValidator({ errorOnRelativeLinks: false })],
			title: 'CARP Documentation',
			description: 'Technical documentation for the Copenhagen Research Platform (CARP).',
			logo: { src: './src/assets/carp.svg', replacesTitle: true },
			favicon: '/favicon.svg',
			customCss: ['./src/styles/carp.css'],
			editLink: { baseUrl: 'https://github.com/carp-dk/carp-docs-starlight/edit/main/' },
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/carp-dk' },
				{ icon: 'linkedin', label: 'LinkedIn', href: 'https://www.linkedin.com/company/carp-dk/' },
				{ icon: 'discord', label: 'Discord', href: 'https://discord.gg/sswpqGvnf5' },
				{ icon: 'email', label: 'Support', href: 'mailto:support@carp.dk' },
			],
			sidebar: [
				{
					label: 'Quick Start',
					items: [
						'start',
						'start/key-concepts',
						'start/first-app',
						{
							label: 'Choosing storage',
							items: [
								{ label: 'Overview', slug: 'start/where-data-goes' },
								'start/storage-phone',
								'start/storage-caws',
								'start/storage-own-server',
							],
						},
						'start/next-steps',
					],
				},
				{
					label: 'CARP Studies app',
					items: [
						{ label: 'Overview', slug: 'studies-app' },
						'studies-app/join-a-study',
						'studies-app/using-the-app',
						'studies-app/run-your-study',
					],
				},
				{
					label: 'Architecture',
					items: ['architecture'],
				},
				{
					label: 'CARP Mobile Sensing',
					items: [
						'carp-mobile-sensing',
						'carp-mobile-sensing/install-and-configure',
						'carp-mobile-sensing/architecture',
						{
							label: 'Domain',
							collapsed: true,
							items: [
								'carp-mobile-sensing/domain',
								'carp-mobile-sensing/domain/study-protocol',
								'carp-mobile-sensing/domain/triggers',
								'carp-mobile-sensing/domain/tasks',
								'carp-mobile-sensing/domain/measures-and-data',
								'carp-mobile-sensing/domain/devices',
								'carp-mobile-sensing/domain/data-endpoints-and-privacy',
								'carp-mobile-sensing/domain/json-serialization',
							],
						},
						{
							label: 'Runtime',
							collapsed: true,
							items: [
								'carp-mobile-sensing/runtime',
								'carp-mobile-sensing/runtime/client-and-study-controller',
								'carp-mobile-sensing/runtime/executors',
								'carp-mobile-sensing/runtime/app-tasks',
								'carp-mobile-sensing/runtime/devices-and-permissions',
							],
						},
						{
							label: 'Infrastructure',
							collapsed: true,
							items: [
								'carp-mobile-sensing/infrastructure',
								'carp-mobile-sensing/infrastructure/data-managers',
								'carp-mobile-sensing/infrastructure/deployment-and-persistence',
								'carp-mobile-sensing/infrastructure/notifications-and-background',
								'carp-mobile-sensing/infrastructure/settings-and-logging',
							],
						},
						{
							label: 'Sampling packages',
							collapsed: true,
							items: [
								'carp-mobile-sensing/sampling-packages',
								'carp-mobile-sensing/sampling-packages/how-they-work',
								'carp-mobile-sensing/sampling-packages/available-packages',
								{
									label: 'Create your own package',
									collapsed: true,
									items: [
										'carp-mobile-sensing/sampling-packages/create-your-own',
										'carp-mobile-sensing/sampling-packages/create-your-own/data',
										'carp-mobile-sensing/sampling-packages/create-your-own/probe',
										'carp-mobile-sensing/sampling-packages/create-your-own/device-manager',
										'carp-mobile-sensing/sampling-packages/create-your-own/sampling-package',
										'carp-mobile-sensing/sampling-packages/create-your-own/publish',
									],
								},
							],
						},
						'carp-mobile-sensing/run-in-production',
						{
							label: 'Github',
							link: 'https://github.com/carp-dk/carp.sensing-flutter',
							attrs: {
								target: '_blank',
							},
						},
						{
							label: 'Pub',
							link: 'https://pub.dev/packages/carp_mobile_sensing',
							attrs: {
								target: '_blank',
							},
						},
					],
					collapsed: true,
				},
				{
					label: 'Health Plugin',
					items: [
						{
							label: 'Getting Started',
							items: [
								'packages/flutter-health-plugin',
								'packages/flutter-health-plugin/install',
								'packages/flutter-health-plugin/quickstart',
							],
						},
						{
							label: 'Core Concepts',
							items: [
								'packages/flutter-health-plugin/permissions',
								'packages/flutter-health-plugin/data-types',
								'packages/flutter-health-plugin/health-connect',
							],
						},
						{
							label: 'Reading Data',
							items: [
								'packages/flutter-health-plugin/read',
								'packages/flutter-health-plugin/read/basic',
								'packages/flutter-health-plugin/read/interval',
								'packages/flutter-health-plugin/read/aggregate',
								'packages/flutter-health-plugin/read/steps',
							],
						},
						{
							label: 'Writing Data',
							items: [
								'packages/flutter-health-plugin/write',
								'packages/flutter-health-plugin/write/basic',
								'packages/flutter-health-plugin/write/workouts',
								'packages/flutter-health-plugin/write/blood',
								'packages/flutter-health-plugin/write/nutrition',
								'packages/flutter-health-plugin/write/specialized',
							],
						},
						{
							label: 'Deleting Data',
							items: ['packages/flutter-health-plugin/delete'],
						},
						{
							label: 'Platform Setup',
							items: [
								'packages/flutter-health-plugin/setup/android',
								'packages/flutter-health-plugin/setup/ios',
							],
						},
						{
							label: 'API Reference',
							items: [
								'packages/flutter-health-plugin/api',
								'packages/flutter-health-plugin/api/health-class',
								'packages/flutter-health-plugin/api/data-models',
								'packages/flutter-health-plugin/api/enums',
							],
						},
						{
							label: 'Github',
							link: 'https://github.com/carp-dk/carp-health-flutter',
							attrs: {
								target: '_blank',
							},
						},
						{
							label: 'Pub',
							link: 'https://pub.dev/packages/health',
							attrs: {
								target: '_blank',
							},
						},
					],
					collapsed: true,
				},
				{
					label: 'Debug Toolkit',
					items: [
						{
							label: 'Getting Started',
							items: [
								'packages/debug-toolkit',
								'packages/debug-toolkit/installation',
								'packages/debug-toolkit/quickstart',
								'packages/debug-toolkit/production',
							],
						},
						{
							label: 'Guides',
							items: [
								'packages/debug-toolkit/environment',
								'packages/debug-toolkit/data-sources',
								'packages/debug-toolkit/built-in-tools',
								'packages/debug-toolkit/custom-tools',
							],
						},
						{
							label: 'GitHub',
							link: 'https://github.com/carp-dk/carp_debug_flutter',
							attrs: {
								target: '_blank',
							},
						},
						{
							label: 'Pub.dev',
							link: 'https://pub.dev/packages/carp_debug_flutter',
							attrs: {
								target: '_blank',
							},
						},
					],
					collapsed: true,
				},
				{
					label: 'Apple Watch Sensing',
					items: [
						{
							label: 'Getting Started',
							items: [
								'packages/apple-watch',
								'packages/apple-watch/installation',
								'packages/apple-watch/quickstart',
							],
						},
						{
							label: 'The Watch App',
							items: [
								'packages/apple-watch/watch-app',
								'packages/apple-watch/watch-app/xcode-setup',
								'packages/apple-watch/watch-app/permissions',
								'packages/apple-watch/watch-app/source-code',
								'packages/apple-watch/watch-app/build-and-verify',
							],
						},
						{
							label: 'Core Concepts',
							items: [
								'packages/apple-watch/concepts/architecture',
								'packages/apple-watch/concepts/configuration',
								'packages/apple-watch/concepts/data-types',
								'packages/apple-watch/concepts/runtime-state',
							],
						},
						{
							label: 'Reference',
							items: [
								'packages/apple-watch/reference/api',
								'packages/apple-watch/reference/watch-settings',
							],
						},
						{
							label: 'GitHub',
							link: 'https://github.com/carp-dk/carp_aware_package',
							attrs: {
								target: '_blank',
							},
						},
						{
							label: 'Pub.dev',
							link: 'https://pub.dev/packages/carp_aware_package',
							attrs: {
								target: '_blank',
							},
						},
					],
					collapsed: true,
				},
				{
					label: 'API Reference',
					items: apiSidebar,
					collapsed: true,
				},
			],
		}),
	],
});
