// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';
import starlightLinksValidator from 'starlight-links-validator';
import { existsSync, readFileSync } from 'node:fs';
import { satteri } from '@astrojs/markdown-satteri';
import { defineHastPlugin } from 'satteri';

// Generated by scripts/api/generate.mjs; absent until the API reference has been generated.
const apiSidebar = existsSync('./src/api-sidebar.json')
? JSON.parse(readFileSync('./src/api-sidebar.json', 'utf8'))
: ['api-reference'];

// Rewrites guide links to pub.dev API docs onto our generated API pages (map from scripts/api/generate.mjs),
// and prefixes root links ("/start/") with the base path, so content works under /carp-docs-starlight.
// ponytail: regex on raw HTML nodes; drop the base part once docs.carp.dk serves from the root.
const apiLinks = existsSync('./src/api-links.json') ? JSON.parse(readFileSync('./src/api-links.json', 'utf8')) : {};
const base = (process.env.BASE_PATH ?? '/').replace(/\/$/, '');
const toApi = (v) => {
const m = v.match(/^https?:\/\/pub\.(?:dev|dartlang\.org)\/documentation\/([^/]+)\/[^/]+\/?([^#]*)/);
const path = m && (m[2] || 'index.html');
return (m && (apiLinks[`${m[1]}/${path}`] ?? apiLinks[`${m[1]}/~/${path.replace(/^[^/]+\//, '')}`])) ?? v; // #anchors dropped
};
const withBase = (v) => (/^\/(?!\/)/.test(v) && !v.startsWith(`${base}/`) ? base + v : v);
const fix = (v) => (typeof v === 'string' ? withBase(toApi(v)) : v);
const linksPlugin = defineHastPlugin({
name: 'api-and-base-links',
element: {
filter: ['a', 'img'],
visit(node, ctx) {
for (const k of ['href', 'src']) if (fix(node.properties[k]) !== node.properties[k]) ctx.setProperty(node, k, fix(node.properties[k]));
},
},
mdxJsxFlowElement: {
filter: ['LinkCard', 'LinkButton', 'a', 'img', 'video'],
visit(node, ctx) {
for (const a of node.attributes) if (['href', 'src'].includes(a.name) && fix(a.value) !== a.value) ctx.setProperty(node, a.name, fix(a.value));
},
},
raw(node, ctx) {
const value = node.value.replace(/(href|src)="([^"]*)"/g, (_, k, v) => `${k}="${fix(v)}"`);
if (value !== node.value) ctx.replaceNode(node, { type: 'raw', value });
},
});

const basePath = (process.env.BASE_PATH ?? '/').replace(/\/$/, '');

export default defineConfig({
		site: process.env.SITE_URL ?? 'https://docs.carp.dk',
	redirects: {
		'/architecture': `${basePath}/start/how-carp-fits/`,
		'/start/first-app': `${basePath}/carp-mobile-sensing/build-your-own-app/design/`,
		'/start/design': `${basePath}/carp-mobile-sensing/build-your-own-app/design/`,
		'/start/build': `${basePath}/carp-mobile-sensing/build-your-own-app/build/`,
		'/start/deploy': `${basePath}/carp-mobile-sensing/build-your-own-app/deploy/`,
		'/start/collect': `${basePath}/carp-mobile-sensing/build-your-own-app/collect/`,
		'/start/where-data-goes': `${basePath}/backends/where-data-goes/`,
		'/start/storage-phone': `${basePath}/backends/where-data-goes/phone/`,
		'/start/storage-caws': `${basePath}/backends/where-data-goes/caws/`,
		'/start/storage-own-server': `${basePath}/backends/where-data-goes/own-server/`,
		'/start/define-your-protocol': `${basePath}/start/configure-your-study/`,
		'/studies-app': `${basePath}/start/run-your-study/`,
		'/studies-app/join-a-study': `${basePath}/start/run-your-study/what-participants-see/`,
		'/studies-app/using-the-app': `${basePath}/start/run-your-study/what-participants-see/`,
		'/studies-app/run-your-study': `${basePath}/start/run-your-study/on-your-phone/`,
		'/carp-mobile-sensing/using-carp-mobile-sensing': `${basePath}/carp-mobile-sensing/runtime/client-and-study-controller/`,
		'/carp-mobile-sensing/software-architecture': `${basePath}/carp-mobile-sensing/architecture/`,
		'/carp-mobile-sensing/domain-model': `${basePath}/carp-mobile-sensing/domain/`,
		'/carp-mobile-sensing/measure-types': `${basePath}/carp-mobile-sensing/sampling-packages/available-packages/`,
		'/carp-mobile-sensing/data-managers': `${basePath}/carp-mobile-sensing/infrastructure/data-managers/`,
		'/carp-mobile-sensing/app-task-model': `${basePath}/carp-mobile-sensing/runtime/app-tasks/`,
		'/carp-mobile-sensing/data-transformation-and-privacy': `${basePath}/carp-mobile-sensing/domain/data-endpoints-and-privacy/`,
		'/carp-mobile-sensing/extending-carp-mobile-sensing': `${basePath}/carp-mobile-sensing/sampling-packages/create-your-own/`,
		'/carp-mobile-sensing/best-practice': `${basePath}/carp-mobile-sensing/run-in-production/`,
		'/packages/flutter-health-plugin/api/data-models': `${basePath}/plugins/health/api/data-models/`,
		'/packages/flutter-health-plugin/api/enums': `${basePath}/plugins/health/api/enums/`,
		'/packages/flutter-health-plugin/api/health-class': `${basePath}/plugins/health/api/health-class/`,
		'/packages/flutter-health-plugin/api': `${basePath}/plugins/health/api/`,
		'/packages/flutter-health-plugin/data-types': `${basePath}/plugins/health/data-types/`,
		'/packages/flutter-health-plugin/delete': `${basePath}/plugins/health/delete/`,
		'/packages/flutter-health-plugin/health-connect': `${basePath}/plugins/health/health-connect/`,
		'/packages/flutter-health-plugin': `${basePath}/plugins/health/`,
		'/packages/flutter-health-plugin/install': `${basePath}/plugins/health/install/`,
		'/packages/flutter-health-plugin/permissions': `${basePath}/plugins/health/permissions/`,
		'/packages/flutter-health-plugin/quickstart': `${basePath}/plugins/health/quickstart/`,
		'/packages/flutter-health-plugin/read/aggregate': `${basePath}/plugins/health/read/aggregate/`,
		'/packages/flutter-health-plugin/read/basic': `${basePath}/plugins/health/read/basic/`,
		'/packages/flutter-health-plugin/read/data': `${basePath}/plugins/health/read/data/`,
		'/packages/flutter-health-plugin/read': `${basePath}/plugins/health/read/`,
		'/packages/flutter-health-plugin/read/interval': `${basePath}/plugins/health/read/interval/`,
		'/packages/flutter-health-plugin/read/steps': `${basePath}/plugins/health/read/steps/`,
		'/packages/flutter-health-plugin/setup/android': `${basePath}/plugins/health/setup/android/`,
		'/packages/flutter-health-plugin/setup/ios': `${basePath}/plugins/health/setup/ios/`,
		'/packages/flutter-health-plugin/write/basic': `${basePath}/plugins/health/write/basic/`,
		'/packages/flutter-health-plugin/write/blood': `${basePath}/plugins/health/write/blood/`,
		'/packages/flutter-health-plugin/write/data': `${basePath}/plugins/health/write/data/`,
		'/packages/flutter-health-plugin/write': `${basePath}/plugins/health/write/`,
		'/packages/flutter-health-plugin/write/nutrition': `${basePath}/plugins/health/write/nutrition/`,
		'/packages/flutter-health-plugin/write/specialized': `${basePath}/plugins/health/write/specialized/`,
		'/packages/flutter-health-plugin/write/workouts': `${basePath}/plugins/health/write/workouts/`,
		'/packages/debug-toolkit/built-in-tools': `${basePath}/plugins/debug-toolkit/built-in-tools/`,
		'/packages/debug-toolkit/custom-tools': `${basePath}/plugins/debug-toolkit/custom-tools/`,
		'/packages/debug-toolkit/data-sources': `${basePath}/plugins/debug-toolkit/data-sources/`,
		'/packages/debug-toolkit/environment': `${basePath}/plugins/debug-toolkit/environment/`,
		'/packages/debug-toolkit': `${basePath}/plugins/debug-toolkit/`,
		'/packages/debug-toolkit/installation': `${basePath}/plugins/debug-toolkit/installation/`,
		'/packages/debug-toolkit/production': `${basePath}/plugins/debug-toolkit/production/`,
		'/packages/debug-toolkit/quickstart': `${basePath}/plugins/debug-toolkit/quickstart/`,
		'/packages/apple-watch/concepts/architecture': `${basePath}/wearables/apple-watch/concepts/architecture/`,
		'/packages/apple-watch/concepts/configuration': `${basePath}/wearables/apple-watch/concepts/configuration/`,
		'/packages/apple-watch/concepts/data-types': `${basePath}/wearables/apple-watch/concepts/data-types/`,
		'/packages/apple-watch/concepts/runtime-state': `${basePath}/wearables/apple-watch/concepts/runtime-state/`,
		'/packages/apple-watch': `${basePath}/wearables/apple-watch/`,
		'/packages/apple-watch/installation': `${basePath}/wearables/apple-watch/installation/`,
		'/packages/apple-watch/quickstart': `${basePath}/wearables/apple-watch/quickstart/`,
		'/packages/apple-watch/reference/api': `${basePath}/wearables/apple-watch/reference/api/`,
		'/packages/apple-watch/reference/watch-settings': `${basePath}/wearables/apple-watch/reference/watch-settings/`,
		'/packages/apple-watch/watch-app/build-and-verify': `${basePath}/wearables/apple-watch/watch-app/build-and-verify/`,
		'/packages/apple-watch/watch-app': `${basePath}/wearables/apple-watch/watch-app/`,
		'/packages/apple-watch/watch-app/permissions': `${basePath}/wearables/apple-watch/watch-app/permissions/`,
		'/packages/apple-watch/watch-app/source-code': `${basePath}/wearables/apple-watch/watch-app/source-code/`,
		'/packages/apple-watch/watch-app/xcode-setup': `${basePath}/wearables/apple-watch/watch-app/xcode-setup/`,
	},
	base: process.env.BASE_PATH ?? '/',
markdown: { processor: satteri({ hastPlugins: [linksPlugin] }) },
	integrations: [
		mermaid({
			autoTheme: true,
			mermaidConfig: {
				themeVariables: { fontFamily: 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif', fontSize: '15px' },
				flowchart: { curve: 'basis', padding: 14, nodeSpacing: 28, rankSpacing: 48 },
				sequence: { mirrorActors: false, actorMargin: 48, boxMargin: 8, noteMargin: 10, messageMargin: 36, actorFontSize: 15, messageFontSize: 15, noteFontSize: 14 },
			},
		}), // must come before starlight; colours are in src/styles/carp.css
		starlight({
			plugins: [starlightLinksValidator({ errorOnRelativeLinks: false })],
			title: 'CARP Documentation',
			description: 'Technical documentation for the Copenhagen Research Platform (CARP).',
			logo: { src: './src/assets/carp.svg', replacesTitle: true },
			favicon: '/favicon.svg',
			customCss: ['./src/styles/carp.css'],
			expressiveCode: { defaultProps: { overridesByLang: { 'xml,ruby,kotlin': { wrap: true } } } },
			editLink: { baseUrl: 'https://github.com/carp-dk/carp-docs-starlight/edit/main/' },
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/carp-dk' },
				{ icon: 'linkedin', label: 'LinkedIn', href: 'https://www.linkedin.com/company/carp-dk/' },
				{ icon: 'discord', label: 'Discord', href: 'https://discord.gg/sswpqGvnf5' },
				{ icon: 'email', label: 'Support', href: 'mailto:support@carp.dk' },
			],
			sidebar: [
				{
					label: 'CARP Framework',
					items: [
						{
							label: 'Quick Start',
							items: [
								'start',
								'start/key-concepts',
								'start/how-carp-fits',
								'start/configure-your-study',
								{
									label: 'Step 2 · Run your study',
									items: [
										{ label: 'Overview', slug: 'start/run-your-study' },
										'start/run-your-study/on-your-phone',
										'start/run-your-study/go-live',
										'start/run-your-study/what-participants-see',
									],
								},
								'start/make-it-your-own',
								'start/components',
								'start/next-steps',
							],
						},
						{
							label: 'CARP Mobile Sensing',
							collapsed: true,
							items: [
								'carp-mobile-sensing',
								{ label: 'Install', slug: 'carp-mobile-sensing/install-and-configure' },
								{
									label: 'Build your own app',
									collapsed: true,
									items: ['carp-mobile-sensing/build-your-own-app/design', 'carp-mobile-sensing/build-your-own-app/build', 'carp-mobile-sensing/build-your-own-app/deploy', 'carp-mobile-sensing/build-your-own-app/collect'],
								},
								'carp-mobile-sensing/architecture',
								{
									label: 'Domain',
									collapsed: true,
									items: [{ label: 'Overview', slug: 'carp-mobile-sensing/domain' }, 'carp-mobile-sensing/domain/study-protocol', 'carp-mobile-sensing/domain/triggers', 'carp-mobile-sensing/domain/tasks', 'carp-mobile-sensing/domain/measures-and-data', 'carp-mobile-sensing/domain/devices', 'carp-mobile-sensing/domain/data-endpoints-and-privacy', 'carp-mobile-sensing/domain/json-serialization'],
								},
								{
									label: 'Runtime',
									collapsed: true,
									items: [{ label: 'Overview', slug: 'carp-mobile-sensing/runtime' }, 'carp-mobile-sensing/runtime/client-and-study-controller', 'carp-mobile-sensing/runtime/executors', 'carp-mobile-sensing/runtime/app-tasks', 'carp-mobile-sensing/runtime/devices-and-permissions'],
								},
								{
									label: 'Infrastructure',
									collapsed: true,
									items: [{ label: 'Overview', slug: 'carp-mobile-sensing/infrastructure' }, 'carp-mobile-sensing/infrastructure/data-managers', 'carp-mobile-sensing/infrastructure/deployment-and-persistence', 'carp-mobile-sensing/infrastructure/notifications-and-background', 'carp-mobile-sensing/infrastructure/settings-and-logging'],
								},
								{
									label: 'Sampling packages',
									collapsed: true,
									items: [
										{ label: 'Overview', slug: 'carp-mobile-sensing/sampling-packages' },
										'carp-mobile-sensing/sampling-packages/how-they-work',
										'carp-mobile-sensing/sampling-packages/available-packages',
										{
											label: 'Create your own package',
											collapsed: true,
											items: [{ label: 'Overview', slug: 'carp-mobile-sensing/sampling-packages/create-your-own' }, 'carp-mobile-sensing/sampling-packages/create-your-own/data', 'carp-mobile-sensing/sampling-packages/create-your-own/probe', 'carp-mobile-sensing/sampling-packages/create-your-own/device-manager', 'carp-mobile-sensing/sampling-packages/create-your-own/sampling-package', 'carp-mobile-sensing/sampling-packages/create-your-own/publish'],
										},
									],
								},
								'carp-mobile-sensing/run-in-production',
								{ label: 'GitHub', link: 'https://github.com/carp-dk/carp.sensing-flutter', attrs: { target: '_blank' } },
								{ label: 'pub.dev', link: 'https://pub.dev/packages/carp_mobile_sensing', attrs: { target: '_blank' } },
							],
						},
						{
							label: 'Sampling Packages',
							collapsed: true,
							items: [
								{ label: 'Health', collapsed: true, items: [{ autogenerate: { directory: 'sampling-packages/health' } }] },
								{ label: 'Context', collapsed: true, items: [{ autogenerate: { directory: 'sampling-packages/context' } }] },
								{ label: 'Surveys & Cognitive Tests', collapsed: true, items: [{ autogenerate: { directory: 'sampling-packages/survey' } }] },
								{ label: 'Audio', collapsed: true, items: [{ autogenerate: { directory: 'sampling-packages/audio' } }] },
								{ label: 'Connectivity', collapsed: true, items: [{ autogenerate: { directory: 'sampling-packages/connectivity' } }] },
								{ label: 'Communication', collapsed: true, items: [{ autogenerate: { directory: 'sampling-packages/communication' } }] },
								{ label: 'Apps', collapsed: true, items: [{ autogenerate: { directory: 'sampling-packages/apps' } }] },
							],
						},
						{
							label: 'Wearables',
							collapsed: true,
							items: [
								{
									label: 'Apple Watch',
									collapsed: true,
									items: [
										'wearables/apple-watch',
										'wearables/apple-watch/installation',
										'wearables/apple-watch/quickstart',
										{ label: 'Watch App', items: ['wearables/apple-watch/watch-app', 'wearables/apple-watch/watch-app/xcode-setup', 'wearables/apple-watch/watch-app/permissions', 'wearables/apple-watch/watch-app/source-code', 'wearables/apple-watch/watch-app/build-and-verify'] },
										'wearables/apple-watch/concepts/configuration', 'wearables/apple-watch/concepts/data-types', 'wearables/apple-watch/concepts/architecture', 'wearables/apple-watch/concepts/runtime-state', 'wearables/apple-watch/reference/watch-settings', 'wearables/apple-watch/reference/api',
										{ label: 'GitHub', link: 'https://github.com/carp-dk/carp_aware_package', attrs: { target: '_blank' } },
										{ label: 'pub.dev', link: 'https://pub.dev/packages/carp_aware_package', attrs: { target: '_blank' } },
									],
								},
								{ label: 'Polar', collapsed: true, items: [{ autogenerate: { directory: 'wearables/polar' } }] },
								{ label: 'Movesense', collapsed: true, items: [{ autogenerate: { directory: 'wearables/movesense' } }] },
								{ label: 'Movisens', collapsed: true, items: [{ autogenerate: { directory: 'wearables/movisens' } }] },
								{ label: 'eSense', collapsed: true, items: [{ autogenerate: { directory: 'wearables/esense' } }] },
							],
						},
						{
							label: 'Backends',
							collapsed: true,
							items: [
								{
									label: 'Where data goes',
									items: [{ label: 'Overview', slug: 'backends/where-data-goes' }, 'backends/where-data-goes/phone', 'backends/where-data-goes/caws', 'backends/where-data-goes/own-server'],
								},
								{ label: 'CAWS Client', collapsed: true, items: [{ autogenerate: { directory: 'backends/carp-webservices' } }] },
								{ label: 'CAWS Data Backend', collapsed: true, items: [{ autogenerate: { directory: 'backends/carp-backend' } }] },
								{ label: 'Firebase', collapsed: true, items: [{ autogenerate: { directory: 'backends/firebase' } }] },
							],
						},
					],
				},
				{
					label: 'Plugins',
					items: [
						{
							label: 'Health Plugin',
							collapsed: true,
							items: [
								'plugins/health',
								'plugins/health/install',
								'plugins/health/quickstart',
								{ label: 'Platform setup', items: ['plugins/health/setup/android', 'plugins/health/setup/ios'] },
								'plugins/health/permissions',
								'plugins/health/data-types',
								'plugins/health/health-connect',
								{ label: 'Reading data', items: ['plugins/health/read', 'plugins/health/read/basic', 'plugins/health/read/interval', 'plugins/health/read/aggregate', 'plugins/health/read/steps'] },
								{ label: 'Writing data', items: ['plugins/health/write', 'plugins/health/write/basic', 'plugins/health/write/workouts', 'plugins/health/write/blood', 'plugins/health/write/nutrition', 'plugins/health/write/specialized'] },
								{ label: 'Deleting data', slug: 'plugins/health/delete' },
								{ label: 'API', items: ['plugins/health/api', 'plugins/health/api/health-class', 'plugins/health/api/data-models', 'plugins/health/api/enums'] },
								{ label: 'GitHub', link: 'https://github.com/carp-dk/carp-health-flutter', attrs: { target: '_blank' } },
								{ label: 'pub.dev', link: 'https://pub.dev/packages/health', attrs: { target: '_blank' } },
							],
						},
						{
							label: 'Debug Toolkit',
							collapsed: true,
							items: [
								'plugins/debug-toolkit',
								'plugins/debug-toolkit/installation',
								'plugins/debug-toolkit/quickstart',
								'plugins/debug-toolkit/environment',
								'plugins/debug-toolkit/data-sources',
								'plugins/debug-toolkit/built-in-tools',
								'plugins/debug-toolkit/custom-tools',
								'plugins/debug-toolkit/production',
								{ label: 'GitHub', link: 'https://github.com/carp-dk/carp_debug_flutter', attrs: { target: '_blank' } },
								{ label: 'pub.dev', link: 'https://pub.dev/packages/carp_debug_flutter', attrs: { target: '_blank' } },
							],
						},
					],
				},
				{
					label: 'API Reference',
					items: apiSidebar,
					collapsed: true,
				},
			],
		}),
	],
});
